Addes Sphinx documentation.
Added napoleon extension
Added dependencies for sphinx to dev profile
[ci] Added sphinx doc action

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -71,6 +71,7 @@ jobs:
           pip install .[dev]
 
       - name: Run pytest
+        id: pytest
         run: pytest
 
       - name: Notify Slack
@@ -84,3 +85,35 @@ jobs:
           notify_when: "failure"
         env:
           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_NOTIFICATIONS_WEBHOOK_URL }}
+
+  sphinx:
+    runs-on: ubuntu-latest
+    if: steps.pytest.outcome == "success" # Ensures that documentation is only rebuilt, if no errors are present
+
+    steps:
+      - name: Checkout repo
+        uses: actions/checkout@v1
+
+      - name: Build sphinx
+        uses: ammaraskar/sphinx-action@master
+        with:
+          docs-folder: "docs/"
+
+      - name: Commit documentation changes
+        run: |
+          git clone https://github.com/qubrabench/qubrabench.git --branch gh-pages --single-branch gh-pages
+          cp -r docs/_build/html/* gh-pages/
+          cd gh-pages
+          git config --local user.email "action@github.com"
+          git config --local user.name "GitHub Action"
+          git add .
+          git commit -m "Update documentation" -a || true
+          # The above command will fail if no changes were present, so we ignore
+          # the return code.
+
+      - name: Push changes
+        uses: ad-m/github-push-action@master
+        with:
+          branch: gh-pages
+          directory: gh-pages
+          github_token: ${{ secrets.GITHUB_TOKEN }}
